require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "config/**/*"
    - "node_modules/**/*"
  NewCops: enable

Metrics/LineLength:
  Max: 100

Layout/BlockLength:
  Exclude:
    - "config/**/*"
    - "spec/**/*"
    - "lib/tasks/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - "app/presenters/**/*"
